# Generated by Django 4.1.3 on 2022-12-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naiss', models.DateField(verbose_name='date naissance')),
                ('lieu_naiss', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('num_CNI', models.CharField(max_length=20)),
                ('num_passeport', models.CharField(max_length=40)),
                ('titreSej', models.CharField(max_length=20)),
                ('numero_permis', models.CharField(max_length=20)),
                ('num_CNPS', models.CharField(max_length=20)),
                ('NUI', models.CharField(max_length=40)),
                ('num_actenais', models.CharField(max_length=40)),
                ('nationalite_origine', models.CharField(max_length=50)),
                ('autre_nationalite', models.CharField(max_length=50)),
                ('region_origine', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('commune_naissance', models.CharField(max_length=30)),
                ('nom_marital', models.CharField(max_length=100)),
                ('pseudonyme', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('fixe', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=200)),
                ('statut_marital', models.CharField(max_length=10)),
                ('parents', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('groupe_sanguin', models.CharField(max_length=1)),
                ('alergies', models.CharField(max_length=200)),
                ('pathologies', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=40)),
                ('catégorie_socioprofessionnal', models.CharField(max_length=40)),
                ('casier', models.CharField(max_length=20)),
                ('Biométrie', models.CharField(max_length=400)),
                ('marque', models.CharField(max_length=10)),
                ('tache_naissance', models.CharField(max_length=10)),
            ],
        ),
    ]
