# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Biométrie',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='patient',
            name='NUI',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alergies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='autre_nationalite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='casier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='catégorie_socioprofessionnal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='commune_naissance',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naiss',
            field=models.DateField(blank=True, verbose_name='date naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='descendants',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fixe',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fonction',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_naiss',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marque',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationalite_origine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom_marital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_CNI',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_CNPS',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_actenais',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_passeport',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parents',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathologies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pseudonyme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region_origine',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut_marital',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tache_naissance',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='titreSej',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
