# Generated by Django 4.1.3 on 2022-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Biométrie',
            new_name='biometrie',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='catégorie_socioprofessionnal',
            new_name='categorie_socioprofessionnal',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_passeport',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
