# Generated by Django 4.1.3 on 2022-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0003_rename_biométrie_patient_biometrie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
