# Generated by Django 4.1.3 on 2022-12-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0005_remove_patient_nui_remove_patient_alergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='etranger',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
