# Generated by Django 4.1.3 on 2022-12-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0006_patient_etranger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
